//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ConvexDecomposition {

public interface IVHACD {
  void Cancel();
  bool Compute(float[] points, uint stridePoints, uint countPoints, int[] triangles, uint strideTriangles, uint countTriangles, Parameters arg6);
  bool Compute(double[] points, uint stridePoints, uint countPoints, int[] triangles, uint strideTriangles, uint countTriangles, Parameters arg6);
  uint GetNConvexHulls();
  void GetConvexHull(uint index, ConvexHull ch);
  void Clean();
  void Release();
  bool OCLInit(global::System.IntPtr oclDevice, UserLogger logger);
  bool OCLInit(global::System.IntPtr oclDevice);
  bool OCLRelease(UserLogger logger);
  bool OCLRelease();
  bool IsReady();
}

}
