//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ConvexDecomposition {

class VHACDBridge {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="SWIGRegisterExceptionCallbacks_VHACDFactory")]
    public static extern void SWIGRegisterExceptionCallbacks_VHACDFactory(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_VHACDFactory")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_VHACDFactory(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_VHACDFactory(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_VHACDFactory(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(VHACDBridge)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(VHACDBridge)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="SWIGRegisterStringCallback_VHACDFactory")]
    public static extern void SWIGRegisterStringCallback_VHACDFactory(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_VHACDFactory(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static VHACDBridge() {
  }


  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_VERSION_MAJOR_get")]
  public static extern int VHACD_VERSION_MAJOR_get();

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_VERSION_MINOR_get")]
  public static extern int VHACD_VERSION_MINOR_get();

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_Cancel")]
  public static extern void VHACD_Cancel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_Compute__SWIG_0")]
  public static extern bool VHACD_Compute__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]float[] jarg2, uint jarg3, uint jarg4, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]int[] jarg5, uint jarg6, uint jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_Compute__SWIG_1")]
  public static extern bool VHACD_Compute__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]double[] jarg2, uint jarg3, uint jarg4, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]int[] jarg5, uint jarg6, uint jarg7, global::System.Runtime.InteropServices.HandleRef jarg8);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_GetNConvexHulls")]
  public static extern uint VHACD_GetNConvexHulls(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_GetConvexHull")]
  public static extern void VHACD_GetConvexHull(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_Clean")]
  public static extern void VHACD_Clean(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_Release")]
  public static extern void VHACD_Release(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_OCLInit__SWIG_0")]
  public static extern bool VHACD_OCLInit__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_OCLInit__SWIG_1")]
  public static extern bool VHACD_OCLInit__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_OCLRelease__SWIG_0")]
  public static extern bool VHACD_OCLRelease__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_OCLRelease__SWIG_1")]
  public static extern bool VHACD_OCLRelease__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_IsReady")]
  public static extern bool VHACD_IsReady(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_delete_UserCallback")]
  public static extern void delete_UserCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_UserCallback_Update")]
  public static extern void UserCallback_Update(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2, double jarg3, double jarg4, string jarg5, string jarg6);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_new_UserCallback")]
  public static extern global::System.IntPtr new_UserCallback();

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_UserCallback_director_connect")]
  public static extern void UserCallback_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, UserCallback.SwigDelegateUserCallback_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_delete_UserLogger")]
  public static extern void delete_UserLogger(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_UserLogger_Log")]
  public static extern void UserLogger_Log(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_new_UserLogger")]
  public static extern global::System.IntPtr new_UserLogger();

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_UserLogger_director_connect")]
  public static extern void UserLogger_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, UserLogger.SwigDelegateUserLogger_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_ConvexHull_m_nPoints_get")]
  public static extern uint ConvexHull_m_nPoints_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_ConvexHull_m_nTriangles_get")]
  public static extern uint ConvexHull_m_nTriangles_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_ConvexHull_m_volume_get")]
  public static extern double ConvexHull_m_volume_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_ConvexHull_GetPoint")]
  public static extern double ConvexHull_GetPoint(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_ConvexHull_GetTriangle")]
  public static extern int ConvexHull_GetTriangle(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_ConvexHull_GetCenter")]
  public static extern double ConvexHull_GetCenter(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_new_ConvexHull")]
  public static extern global::System.IntPtr new_ConvexHull();

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_delete_ConvexHull")]
  public static extern void delete_ConvexHull(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_new_Parameters")]
  public static extern global::System.IntPtr new_Parameters();

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_Init")]
  public static extern void Parameters_Init(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_concavity_set")]
  public static extern void Parameters_m_concavity_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_concavity_get")]
  public static extern double Parameters_m_concavity_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_alpha_set")]
  public static extern void Parameters_m_alpha_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_alpha_get")]
  public static extern double Parameters_m_alpha_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_beta_set")]
  public static extern void Parameters_m_beta_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_beta_get")]
  public static extern double Parameters_m_beta_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_minVolumePerCH_set")]
  public static extern void Parameters_m_minVolumePerCH_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_minVolumePerCH_get")]
  public static extern double Parameters_m_minVolumePerCH_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_callback_set")]
  public static extern void Parameters_m_callback_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_callback_get")]
  public static extern global::System.IntPtr Parameters_m_callback_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_logger_set")]
  public static extern void Parameters_m_logger_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_logger_get")]
  public static extern global::System.IntPtr Parameters_m_logger_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_resolution_set")]
  public static extern void Parameters_m_resolution_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_resolution_get")]
  public static extern uint Parameters_m_resolution_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_maxNumVerticesPerCH_set")]
  public static extern void Parameters_m_maxNumVerticesPerCH_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_maxNumVerticesPerCH_get")]
  public static extern uint Parameters_m_maxNumVerticesPerCH_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_depth_set")]
  public static extern void Parameters_m_depth_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_depth_get")]
  public static extern int Parameters_m_depth_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_planeDownsampling_set")]
  public static extern void Parameters_m_planeDownsampling_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_planeDownsampling_get")]
  public static extern int Parameters_m_planeDownsampling_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_convexhullDownsampling_set")]
  public static extern void Parameters_m_convexhullDownsampling_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_convexhullDownsampling_get")]
  public static extern int Parameters_m_convexhullDownsampling_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_pca_set")]
  public static extern void Parameters_m_pca_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_pca_get")]
  public static extern int Parameters_m_pca_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_mode_set")]
  public static extern void Parameters_m_mode_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_mode_get")]
  public static extern int Parameters_m_mode_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_convexhullApproximation_set")]
  public static extern void Parameters_m_convexhullApproximation_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_convexhullApproximation_get")]
  public static extern int Parameters_m_convexhullApproximation_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_oclAcceleration_set")]
  public static extern void Parameters_m_oclAcceleration_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_oclAcceleration_get")]
  public static extern int Parameters_m_oclAcceleration_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_maxConvexHulls_set")]
  public static extern void Parameters_m_maxConvexHulls_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_Parameters_m_maxConvexHulls_get")]
  public static extern uint Parameters_m_maxConvexHulls_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_delete_Parameters")]
  public static extern void delete_Parameters(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_CreateVHACD")]
  public static extern global::System.IntPtr CreateVHACD();

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_CreateVHACD_ASYNC")]
  public static extern global::System.IntPtr CreateVHACD_ASYNC();

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_VHACD_IVHACD_GetInterfaceCPtr")]
  public static extern global::System.IntPtr VHACD_IVHACD_GetInterfaceCPtr(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_UserCallback_IUserCallback_GetInterfaceCPtr")]
  public static extern global::System.IntPtr UserCallback_IUserCallback_GetInterfaceCPtr(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("vhacd", EntryPoint="CSharp_ConvexDecomposition_UserLogger_IUserLogger_GetInterfaceCPtr")]
  public static extern global::System.IntPtr UserLogger_IUserLogger_GetInterfaceCPtr(global::System.IntPtr jarg1);
}

}
